---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
spec:
  interval: 30s
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  serviceAccountName: kustomize-controller
  interval: 1m
  releaseName: "metrics-server"
  targetNamespace: "kube-system"
  chart:
    spec:
      chart: metrics-server
      version: "3.12.2"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      interval: 24h
  install:
    createNamespace: false
    remediation:
      retries: -1
  upgrade:
    remediation:
      remediateLastFailure: true
  driftDetection:
    mode: enabled
  values:
    args:
    - --kubelet-insecure-tls
