apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  cortex-tenant.yml: |-
    {{- toYaml .Values.config | nindent 4 }}
