{{- if $.Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - list
    - update
    - create
    - patch
- apiGroups:
    - capsule.clastix.io
  resources:
    - tenants
    - tenants/status
  verbs:
    - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "helm.fullname" . }}
subjects:
  - name: {{ include "helm.serviceAccountName" . }}
    kind: ServiceAccount
    namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
rules:
- apiGroups:
    - "coordination.k8s.io"
  resources:
    - leases
  verbs:
    - create
    - get
    - list
    - update
    - patch
    - watch
    - delete
    - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "helm.fullname" . }}
subjects:
  - name: {{ include "helm.serviceAccountName" . }}
    kind: ServiceAccount
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
