
{{- if and $.Values.monitoring.enabled $.Values.monitoring.rules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "helm.fullname" . }}
  namespace: {{ .Values.monitoring.rules.namespace | default .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    {{- with .Values.monitoring.rules.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.monitoring.rules.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  groups:
    {{- toYaml .Values.monitoring.rules.groups | nindent 4 }}
{{- end }}
