name: e2e
permissions: {}

on:
  pull_request:
    branches:
      - "*"
    paths:
      - '.github/workflows/e2e.yml'
      - 'api/**'
      - 'cmd/**'
      - 'internal/**'
      - 'e2e/*'
      - '.ko.yaml'
      - 'go.*'
      - 'main.go'
      - 'Makefile'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  kind:
    name: Kubernetes
    strategy:
      fail-fast: false
      matrix:
        k8s-version:
          - ""
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: 'go.mod'
      - name: e2e testing
        run: KIND_K8S_VERSION="${{ matrix.k8s-version }}" make e2e
